version: 2
updates:
- package-ecosystem: "gomod"
  directory: "/"
  schedule:
    interval: "daily"

- package-ecosystem: "gomod"
  directory: "/assets/catnip"
  schedule:
    interval: "daily"

- package-ecosystem: "gomod"
  directory: "/assets/credhub-service-broker"
  schedule:
    interval: "daily"

- package-ecosystem: "gomod"
  directory: "/assets/go_calls_ruby"
  schedule:
    interval: "daily"

- package-ecosystem: "gomod"
  directory: "/assets/golang"
  schedule:
    interval: "daily"

- package-ecosystem: "gomod"
  directory: "/assets/grpc"
  schedule:
    interval: "daily"

- package-ecosystem: "gomod"
  directory: "/assets/http2"
  schedule:
    interval: "daily"

- package-ecosystem: "gomod"
  directory: "/assets/logging-route-service"
  schedule:
    interval: "daily"

- package-ecosystem: "gomod"
  directory: "/assets/pora"
  schedule:
    interval: "daily"

- package-ecosystem: "gomod"
  directory: "/assets/proxy"
  schedule:
    interval: "daily"

- package-ecosystem: "gomod"
  directory: "/assets/syslog-drain-listener"
  schedule:
    interval: "daily"

- package-ecosystem: "gomod"
  directory: "/assets/tcp-listener"
  schedule:
    interval: "daily"

- package-ecosystem: "gomod"
  directory: "/assets/worker-app"
  schedule:
    interval: "daily"

- package-ecosystem: "gomod"
  directory: "/assets/worker"
  schedule:
    interval: "daily"

- package-ecosystem: "docker"
  directory: "/assets/pora"
  schedule:
    interval: "daily"

- package-ecosystem: "bundler"
  vendor: true
  directory: "/assets/dora"
  schedule:
    interval: "daily"

- package-ecosystem: "bundler"
  vendor: true
  directory: "/assets/go_calls_ruby"
  schedule:
    interval: "daily"

- package-ecosystem: "bundler"
  vendor: true
  directory: "/assets/hello-routing"
  schedule:
    interval: "daily"

- package-ecosystem: "bundler"
  vendor: true
  directory: "/assets/hello-world"
  schedule:
    interval: "daily"

- package-ecosystem: "bundler"
  vendor: true
  directory: "/assets/loggregator-load-generator"
  schedule:
    interval: "daily"

- package-ecosystem: "bundler"
  vendor: true
  directory: "/assets/ruby_simple"
  schedule:
    interval: "daily"

- package-ecosystem: "bundler"
  vendor: true
  directory: "/assets/service_broker"
  schedule:
    interval: "daily"
