# See https://github.com/vmware-tanzu/carvel-vendir/blob/3f713be1c44bbf443658ec3508446102438b9482/docs/vendir-spec.md

apiVersion: vendir.k14s.io/v1alpha1
kind: Config

# declaration of minimum required vendir binary version (optional)
minimumRequiredVersion: 0.8.0

directories:
- path: assets/logging-route-service
  contents:
  - path: .
    git:
      url: https://github.com/cloudfoundry-samples/logging-route-service
      ref: origin/master
    # exclude paths are "placed" on top of include paths (optional)
    excludePaths:
    - ".git/**/*"
