source 'http://rubygems.org'

gem 'sinatra'
gem 'sinatra-activerecord'
gem 'thin'
gem 'amqp'
gem 'redis'
gem 'mongo_mapper'
gem 'bson_ext'
gem 'activemodel-serializers-xml'
gem 'pg'
gem 'httpclient'

