package assets

type Assets struct {
	AspClassic                 string
	Catnip                     string
	CredHubEnabledApp          string
	CredHubServiceBroker       string
	Dora                       string
	DoraZip                    string
	DotnetCore                 map[string]string
	Fuse                       string
	GoCallsRubyZip             string
	Golang                     string
	GRPC                       string
	HelloWorld                 string
	HelloRouting               string
	HTTP2                      string
	Java                       string
	JavaSpringZip              string
	JavaUnwriteableZip         string
	LoggregatorLoadGenerator   string
	LoggregatorLoadGeneratorGo string
	Python                     string
	Node                       string
	NodeWithProcfile           string
	Nora                       string
	Pora                       string
	Php                        string
	Proxy                      string
	RubySimple                 string
	SecurityGroupBuildpack     string
	ServiceBroker              string
	Staticfile                 string
	SyslogDrainListener        string
	Binary                     string
	LoggingRouteService        string
	TCPListener                string
	Wcf                        string
	WindowsWebapp              string
	WindowsWorker              string
	WorkerApp                  string
	MultiPortApp               string
	SpringSleuthZip            string
}

func NewAssets() Assets {
	return Assets{
		AspClassic:           "assets/asp-classic",
		Catnip:               "assets/catnip/bin",
		CredHubEnabledApp:    "assets/credhub-enabled-app/credhub-enabled-app.jar",
		CredHubServiceBroker: "assets/credhub-service-broker",
		Dora:                 "assets/dora",
		DoraZip:              "assets/dora.zip",
		DotnetCore: map[string]string{
			"cflinuxfs3": "assets/dotnet-core/cflinuxfs3",
			"cflinuxfs4": "assets/dotnet-core/cflinuxfs4",
		},
		Fuse:                       "assets/fuse-mount",
		GoCallsRubyZip:             "assets/go_calls_ruby.zip",
		Golang:                     "assets/golang",
		GRPC:                       "assets/grpc",
		HelloRouting:               "assets/hello-routing",
		HelloWorld:                 "assets/hello-world",
		HTTP2:                      "assets/http2",
		Java:                       "assets/java",
		JavaSpringZip:              "assets/java-spring/java-spring.jar",
		JavaUnwriteableZip:         "assets/java-unwriteable-dir/java-unwriteable-dir.jar",
		LoggregatorLoadGenerator:   "assets/loggregator-load-generator",
		LoggregatorLoadGeneratorGo: "assets/loggregator-load-generator-go",
		Node:                       "assets/node",
		NodeWithProcfile:           "assets/node-with-procfile",
		Nora:                       "assets/nora/NoraPublished",
		Pora:                       "assets/pora",
		Php:                        "assets/php",
		Proxy:                      "assets/proxy",
		Python:                     "assets/python",
		RubySimple:                 "assets/ruby_simple",
		SecurityGroupBuildpack:     "assets/security_group_buildpack.zip",
		ServiceBroker:              "assets/service_broker",
		Staticfile:                 "assets/staticfile",
		SyslogDrainListener:        "assets/syslog-drain-listener",
		Binary:                     "assets/binary",
		LoggingRouteService:        "assets/logging-route-service",
		TCPListener:                "assets/tcp-listener",
		Wcf:                        "assets/wcf/Hello.Service.IIS",
		WindowsWebapp:              "assets/webapp",
		WorkerApp:                  "assets/worker-app",
		WindowsWorker:              "assets/worker",
		MultiPortApp:               "assets/multi-port-app",
		SpringSleuthZip:            "assets/spring-sleuth/spring-sleuth.jar",
	}
}
