#!/bin/bash -eux

function main() {
  local capi_url
  capi_url="$(grep -Eo 'https://s3\.amazonaws\.com/capi-releases/capi.*\.tgz' cf-cli-v7/body)"

  cat <<EOT > capi-rc-ops-file/use-capi-rc.yml
- type: replace
  path: /releases/name=capi
  value:
    name: capi
    url: ${capi_url}
    version: latest
EOT
}

main
