---
resources:
- name: cats-pool
  type: pool
  icon: pool
  source:
    uri: git@github.com:cloudfoundry/relint-ci-pools
    branch: main
    pool: cats
    private_key: ((relint_ci_pools_readwrite_deploy_key.private_key))

- name: relint-envs
  type: git
  icon: github
  source:
    branch: main
    uri: git@github.com:cloudfoundry/relint-envs.git
    private_key: ((hagrid_env_readwrite_deploy_key.private_key))

- name: cf-deployment-concourse-tasks
  type: git
  icon: github
  source:
    uri: https://github.com/cloudfoundry/cf-deployment-concourse-tasks.git

- name: runtime-ci
  type: git
  icon: github
  source:
    uri: https://github.com/cloudfoundry/runtime-ci.git

- name: cf-acceptance-tests-develop
  type: git
  icon: github
  source:
    branch: develop
    uri: git@github.com:cloudfoundry/cf-acceptance-tests.git
    private_key: ((cf_acceptance_tests_readwrite_deploy_key.private_key))
    ignore_paths:
    - ci/**
    - .envrc

- name: cf-acceptance-tests-rc
  type: git
  icon: github
  source:
    branch: release-candidate
    uri: git@github.com:cloudfoundry/cf-acceptance-tests.git
    private_key: ((cf_acceptance_tests_readwrite_deploy_key.private_key))
    ignore_paths:
    - ci/**
    - .envrc

- name: cf-acceptance-tests-main
  type: git
  icon: github
  source:
    branch: main
    uri: git@github.com:cloudfoundry/cf-acceptance-tests.git
    private_key: ((cf_acceptance_tests_readwrite_deploy_key.private_key))
    ignore_paths:
    - ci/**
    - .envrc

- name: cf-deployment-main
  type: git
  icon: github
  source:
    uri: git@github.com:cloudfoundry/cf-deployment.git
    private_key: ((cf_deployment_readwrite_deploy_key.private_key))
    ignore_paths:
    - ci/**
    - .envrc

- name: cats-version
  type: semver
  source:
    driver: git
    uri: git@github.com:cloudfoundry/cf-relint-ci-semver.git
    branch: main
    private_key: ((cf_relint_ci_semver_readwrite_deploy_key.private_key))
    git_user: "CF MEGA BOT <cf-mega@pivotal.io>"
    file: cats-version

jobs:
- name: run-unit-tests
  serial: true
  public: true
  plan:
  - in_parallel:
    - get: cf-acceptance-tests-develop
      trigger: true
    - get: runtime-ci
    - get: cf-deployment-main
      passed:
      - smoke-tests
      trigger: true

  - task: run-cats-unit-tests
    file: runtime-ci/tasks/run-cats-unit-tests/task.yml
    input_mapping:
      cf-acceptance-tests: cf-acceptance-tests-develop

  - put: cats-pool
    params:
      claim: cats

- name: acquire-pool-deploy
  public: true
  serial: true
  plan:
  - get: cf-deployment-main
    trigger: true

  - put: cats-pool
    params:
      claim: cats

- name: release-pool-manual
  public: true
  plan:
  - get: cats-pool
  ensure:
    try:
      put: cats-pool
      params:
        release: cats-pool

- name: deploy-cf
  public: true
  plan:
  - in_parallel:
    - get: cats-pool
      passed:
      - acquire-pool-deploy
      trigger: true
    - get: runtime-ci
    - get: cf-deployment-concourse-tasks
    - get: cf-deployment-main
      passed:
      - acquire-pool-deploy
    - get: relint-envs

  - task: bosh-deploy-cf
    file: cf-deployment-concourse-tasks/bosh-deploy/task.yml
    input_mapping:
      bbl-state: relint-envs
      cf-deployment: cf-deployment-main
      ops-files: cf-deployment-main
      vars-files: relint-envs
    params:
      BBL_STATE_DIR: environments/test/cats/bbl-state
      SYSTEM_DOMAIN: cf.cats.env.wg-ard.ci.cloudfoundry.org
      OPS_FILES: |
        operations/use-compiled-releases.yml
        operations/use-internal-lookup-for-route-services.yml
        operations/windows2019-cell.yml
        operations/use-online-windows2019fs.yml
        operations/experimental/use-compiled-releases-windows.yml

  - task: run-bosh-cleanup
    file: cf-deployment-concourse-tasks/bosh-cleanup/task.yml
    input_mapping:
      bbl-state: relint-envs
    params:
      BBL_STATE_DIR: environments/test/cats/bbl-state

  - task: update-integration-configs
    file: cf-deployment-concourse-tasks/update-integration-configs/task.yml
    params:
      BBL_STATE_DIR: environments/test/cats/bbl-state
      CATS_INTEGRATION_CONFIG_FILE: environments/test/cats/integration_config.json
    input_mapping:
      bbl-state: relint-envs
      integration-configs: relint-envs
    ensure:
      put: relint-envs
      params:
        repository: updated-integration-configs
        rebase: true

- name: smoke-tests
  public: true
  plan:
  - in_parallel:
    - get: cats-pool
      passed:
      - deploy-cf
      trigger: true
    - get: relint-envs
    - get: cf-deployment-main
      passed:
      - deploy-cf
    - get: cf-deployment-concourse-tasks

  - task: bosh-run-errand-smoke-tests
    file: cf-deployment-concourse-tasks/run-errand/task.yml
    input_mapping:
      bbl-state: relint-envs
    params:
      BBL_STATE_DIR: environments/test/cats/bbl-state
      ERRAND_NAME: smoke_tests

  - put: cats-pool
    params:
      release: cats-pool

- name: run-cats-vms
  serial: true
  public: true
  plan:
  - in_parallel:
    - get: cats-pool
      passed:
      - run-unit-tests
      trigger: true
    - get: cf-deployment-concourse-tasks
    - get: cf-acceptance-tests-develop
      passed:
      - run-unit-tests
    - get: relint-envs
    - get: cf-deployment-main
      passed:
      - run-unit-tests

  - task: enable-docker-and-tasks
    file: cf-deployment-concourse-tasks/set-feature-flags/task.yml
    attempts: 3
    input_mapping:
      bbl-state: relint-envs
    params:
      BBL_STATE_DIR: environments/test/cats/bbl-state
      SYSTEM_DOMAIN: cf.cats.env.wg-ard.ci.cloudfoundry.org
      ENABLED_FEATURE_FLAGS: |
        diego_docker
        task_creation
        service_instance_sharing

  - task: run-cats
    file: cf-deployment-concourse-tasks/run-cats/task.yml
    input_mapping:
      integration-config: relint-envs
      cf-acceptance-tests: cf-acceptance-tests-develop
    params:
      CONFIG_FILE_PATH: environments/test/cats/integration_config.json
      REPORTER_CONFIG_FILE_PATH: environments/test/cats/reporter_config.json

- name: bless-cats
  public: true
  serial: true
  plan:
  - in_parallel:
    - get: runtime-ci
    - get: cf-acceptance-tests-develop
      passed:
      - run-cats-vms
      trigger: true
    - get: cf-deployment-main
      passed:
      - run-cats-vms
      trigger: true

  - put: cf-acceptance-tests-rc
    params:
      repository: cf-acceptance-tests-develop

  - task: update-cats-cfd-branch
    file: runtime-ci/tasks/update-cats-branch-with-cf-deployment-version/task.yml
    input_mapping:
      cf-deployment: cf-deployment-main
      cf-acceptance-tests: cf-acceptance-tests-rc
    params:
      CATS_BRANCH: release-candidate
      DEPLOY_KEY: ((cf_acceptance_tests_readwrite_deploy_key.private_key))

- name: cleanup-cats
  serial: true
  public: true
  plan:
  - in_parallel:
    - get: cats-pool
      passed:
      - run-cats-vms
      trigger: true
    - get: runtime-ci
    - get: relint-envs

  - task: cleanup-cats
    file: runtime-ci/tasks/cleanup-after-cats/task.yml
    input_mapping:
      integration-config: relint-envs
    params:
      CONFIG_FILE_PATH: environments/test/cats/integration_config.json

  - put: cats-pool
    params:
      release: cats-pool

- name: ship-it-patch
  public: true
  plan:
  - in_parallel:
    - get: cats-version
      params:
        bump: patch
    - get: cf-acceptance-tests-develop
    - get: cf-acceptance-tests-rc
      passed:
      - bless-cats

  - put: cf-acceptance-tests-main
    params:
      repository: cf-acceptance-tests-rc
      tag: cats-version/version
      tag_prefix: v

  - put: cats-version
    params:
      bump: patch

- name: ship-it-minor
  public: true
  plan:
  - in_parallel:
    - get: cats-version
      params:
        bump: minor
    - get: cf-acceptance-tests-develop
    - get: cf-acceptance-tests-rc
      passed:
      - bless-cats

  - put: cf-acceptance-tests-main
    params:
      repository: cf-acceptance-tests-rc
      tag: cats-version/version
      tag_prefix: v

  - put: cats-version
    params:
      bump: minor

- name: ship-it-major
  public: true
  plan:
  - in_parallel:
    - get: cats-version
      params:
        bump: major
    - get: cf-acceptance-tests-develop
    - get: cf-acceptance-tests-rc
      passed:
      - bless-cats

  - put: cf-acceptance-tests-main
    params:
      repository: cf-acceptance-tests-rc
      tag: cats-version/version
      tag_prefix: v

  - put: cats-version
    params:
      bump: major
