---
resource_types:
- name: toolsmiths-cf-pool
  type: docker-image
  source:
    repository: cftoolsmiths/toolsmiths-envs-resource

resources:
- name: relint-envs
  type: git
  icon: github-box
  source:
    branch: master
    uri: git@github.com:cloudfoundry/relint-envs.git
    private_key: ((hagrid_env_readwrite_deploy_key.private_key))

- name: cf-deployment-concourse-tasks
  type: git
  icon: github-box
  source:
    branch: master
    uri: https://github.com/cloudfoundry/cf-deployment-concourse-tasks.git

- name: runtime-ci
  type: git
  icon: github-box
  source:
    branch: master
    uri: https://github.com/cloudfoundry/runtime-ci.git

- name: cf-acceptance-tests-develop
  type: git
  icon: github-box
  source:
    branch: develop
    uri: git@github.com:cloudfoundry/cf-acceptance-tests.git
    private_key: ((cf_acceptance_tests_readwrite_deploy_key.private_key))
    ignore_paths:
    - ci/**
    - .envrc

- name: cf-acceptance-tests-rc
  type: git
  icon: github-box
  source:
    branch: release-candidate
    uri: git@github.com:cloudfoundry/cf-acceptance-tests.git
    private_key: ((cf_acceptance_tests_readwrite_deploy_key.private_key))
    ignore_paths:
    - ci/**
    - .envrc

- name: cf-acceptance-tests-master
  type: git
  icon: github-box
  source:
    branch: master
    uri: git@github.com:cloudfoundry/cf-acceptance-tests.git
    private_key: ((cf_acceptance_tests_readwrite_deploy_key.private_key))
    ignore_paths:
    - ci/**
    - .envrc

- name: cf-deployment-master
  type: git
  icon: github-box
  source:
    branch: master
    uri: git@github.com:cloudfoundry/cf-deployment.git
    private_key: ((cf_deployment_readwrite_deploy_key.private_key))
    ignore_paths:
    - ci/**
    - .envrc

- name: cf-test-helpers
  type: git
  icon: github-box
  source:
    branch: master
    uri: https://github.com/cloudfoundry-incubator/cf-test-helpers

- name: cats-version
  type: semver
  source:
    driver: git
    uri: git@github.com:cloudfoundry/cf-relint-ci-semver.git
    branch: master
    private_key: ((cf_relint_ci_semver_readwrite_deploy_key.private_key))
    git_user: "CF MEGA BOT <cf-mega@pivotal.io>"
    file: cats-version

- name: deliver-tracker-story
  type: tracker
  source:
    token: ((cf_relint_tracker_api_token))
    project_id: "1382120"
    tracker_url: https://www.pivotaltracker.com

- name: toolsmiths-env
  type: toolsmiths-cf-pool
  source:
    api_token: ((toolsmiths_api_token))
    hostname: environments.toolsmiths.cf-app.com
    pool_name: cf-deployment
  tags:
  - vsphere-cf-release-integration

jobs:
- name: bump-cf-test-helpers
  public: true
  plan:
  - in_parallel:
    - get: cf-acceptance-tests-develop
    - get: runtime-ci
    - get: cf-test-helpers
      trigger: true
  - task: run-cf-test-helpers-unit-tests
    file: runtime-ci/tasks/run-cf-test-helpers-unit-tests/task.yml
  - task: bump-cf-test-helpers
    file: runtime-ci/tasks/bump-cf-test-helpers/task.yml
    input_mapping:
      repository: cf-acceptance-tests-develop
  - put: cf-acceptance-tests-develop
    params:
      repository: updated-repository
      rebase: true

- name: unit-test
  serial: true
  public: true
  plan:
  - get: cf-acceptance-tests-develop
    trigger: true
  - get: runtime-ci
  - task: run-cats-unit-tests
    file: runtime-ci/tasks/run-cats-unit-tests/task.yml
    input_mapping:
      cf-acceptance-tests: cf-acceptance-tests-develop

- name: claim-env
  serial: true
  # TODO: make public when the toolsmiths-env resource stops leaking creds
  #public: true
  plan:
  - in_parallel:
    - put: toolsmiths-env
      params:
        action: claim
      tags:
      - vsphere-cf-release-integration
    - get: cf-acceptance-tests-develop
      trigger: true
      passed: [unit-test]
    timeout: 4h

- name: deploy-cf
  serial: true
  # TODO: make public when the toolsmiths-env resource stops leaking creds
  #public: true
  plan:
  - in_parallel:
    - get: toolsmiths-env
      passed:
      - claim-env
      tags:
      - vsphere-cf-release-integration
      trigger: true
    - get: cf-deployment-concourse-tasks
    - get: cf-deployment-master
    - get: cf-acceptance-tests-develop
      passed:
      - claim-env
  - task: bosh-scale-up-cf
    file: cf-deployment-concourse-tasks/bosh-deploy/task.yml
    input_mapping:
      cf-deployment: cf-deployment-master
      ops-files: cf-deployment-master
    params:
      OPS_FILES: |
        operations/use-compiled-releases.yml
        operations/use-internal-lookup-for-route-services.yml
  - in_parallel:
    # - task: open-asgs-for-credhub
    #   file: cf-deployment-concourse-tasks/open-asgs-for-bosh-instance-group/task.yml
    #   params:
    #     INSTANCE_GROUP_NAME: credhub
    #     SECURITY_GROUP_NAME: credhub
    # - task: open-asgs-for-uaa
    #   file: cf-deployment-concourse-tasks/open-asgs-for-bosh-instance-group/task.yml
    #   params:
    #     INSTANCE_GROUP_NAME: uaa
    #     SECURITY_GROUP_NAME: uaa
    - task: enable-docker-and-tasks
      file: cf-deployment-concourse-tasks/set-feature-flags/task.yml
      params:
        ENABLED_FEATURE_FLAGS: |
          diego_docker
          task_creation
          service_instance_sharing

- name: run-cats
  serial: true
  # TODO: make public when the toolsmiths-env resource stops leaking creds
  #public: true
  plan:
  - in_parallel:
    - get: toolsmiths-env
      passed:
      - deploy-cf
      tags:
      - vsphere-cf-release-integration
      trigger: true
    - get: cf-deployment-concourse-tasks
    - get: cf-acceptance-tests-develop
      passed:
      - deploy-cf
    - get: relint-envs

  - task: enable-docker-and-tasks
    file: cf-deployment-concourse-tasks/set-feature-flags/task.yml
    attempts: 3
    input_mapping:
      bbl-state: relint-envs
    params:
      BBL_STATE_DIR: environments/test/cats/bbl-state
      SYSTEM_DOMAIN: cats.cf-app.com
      ENABLED_FEATURE_FLAGS: |
        diego_docker
        task_creation
        service_instance_sharing

  - task: update-integration-configs
    file: cf-deployment-concourse-tasks/update-integration-configs/task.yml
    params:
      CATS_INTEGRATION_CONFIG_FILE: environments/test/cats/integration_config.json
    input_mapping:
      integration-configs: relint-envs

  - task: run-cats
    file: cf-deployment-concourse-tasks/run-cats/task.yml
    input_mapping:
      integration-config: updated-integration-configs
      cf-acceptance-tests: cf-acceptance-tests-develop
    params:
      CONFIG_FILE_PATH: environments/test/cats/integration_config.json
      REPORTER_CONFIG_FILE_PATH: environments/test/cats/reporter_config.json

- name: bless-cats
  public: true
  serial: true
  plan:
  - get: runtime-ci
  - get: cf-acceptance-tests-develop
    trigger: true
    passed:
    - run-cats
  - put: cf-acceptance-tests-rc
    params:
      repository: cf-acceptance-tests-develop
  - put: deliver-tracker-story
    params:
      repos:
        - cf-acceptance-tests-develop
  - task: create-pm-story
    file: runtime-ci/tasks/create-pm-story/task.yml
    input_mapping:
      input-description: version-json
    params:
      TRACKER_STORY_NAME: "New CATs Change has been Blessed!!!"
      TRACKER_STORY_STATE: delivered
      TRACKER_API_TOKEN: ((cf_relint_tracker_api_token))
      DESCRIPTION_FILE: version.json

- name: unclaim-env
  serial: true
  # TODO: make public when the toolsmiths-env resource stops leaking creds
  #public: true
  plan:
  - get: toolsmiths-env
    passed:
    - run-cats
    tags:
    - vsphere-cf-release-integration
    trigger: true
  - put: toolsmiths-env
    params:
      action: unclaim
      env_file: toolsmiths-env/metadata
    tags:
    - vsphere-cf-release-integration

- name: ship-it-patch
  public: true
  plan:
    - do:
      - get: cats-version
        params: {bump: patch}
      - get: cf-acceptance-tests-develop
      - get: cf-acceptance-tests-rc
        passed: [bless-cats]
      - put: cf-acceptance-tests-master
        params:
          repository: cf-acceptance-tests-rc
          tag: cats-version/version
          tag_prefix: v
      - put: cats-version
        params: {bump: patch}

- name: ship-it-minor
  public: true
  plan:
    - do:
      - get: cats-version
        params: {bump: minor}
      - get: cf-acceptance-tests-develop
      - get: cf-acceptance-tests-rc
        passed: [bless-cats]
      - put: cf-acceptance-tests-master
        params:
          repository: cf-acceptance-tests-rc
          tag: cats-version/version
          tag_prefix: v
      - put: cats-version
        params: {bump: minor}

- name: ship-it-major
  public: true
  plan:
    - do:
      - get: cats-version
        params: {bump: major}
      - get: cf-acceptance-tests-develop
      - get: cf-acceptance-tests-rc
        passed: [bless-cats]
      - put: cf-acceptance-tests-master
        params:
          repository: cf-acceptance-tests-rc
          tag: cats-version/version
          tag_prefix: v
      - put: cats-version
        params: {bump: major}
