// This file was generated by counterfeiter
package fakes

import (
	"sync"

	"github.com/cloudfoundry/cf-acceptance-tests/helpers/cli_version_check/cli_version"
)

type FakeCliVersion struct {
	GetVersionStub        func() string
	getVersionMutex       sync.RWMutex
	getVersionArgsForCall []struct{}
	getVersionReturns struct {
		result1 string
	}
}

func (fake *FakeCliVersion) GetVersion() string {
	fake.getVersionMutex.Lock()
	fake.getVersionArgsForCall = append(fake.getVersionArgsForCall, struct{}{})
	fake.getVersionMutex.Unlock()
	if fake.GetVersionStub != nil {
		return fake.GetVersionStub()
	} else {
		return fake.getVersionReturns.result1
	}
}

func (fake *FakeCliVersion) GetVersionCallCount() int {
	fake.getVersionMutex.RLock()
	defer fake.getVersionMutex.RUnlock()
	return len(fake.getVersionArgsForCall)
}

func (fake *FakeCliVersion) GetVersionReturns(result1 string) {
	fake.GetVersionStub = nil
	fake.getVersionReturns = struct {
		result1 string
	}{result1}
}

var _ cli_version.CliVersion = new(FakeCliVersion)
